package domain

import (
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Identifier is the constraint every entity identity must satisfy.
//
// It is the Go counterpart of the C# IBaseIdentifier / ILongIdentifier family: identities are
// strongly typed value objects, so a PartyID can never be passed where an OrderID is expected.
// The idiomatic way to declare one is to embed a primitive identifier:
//
//	type PartyID struct{ domain.UUID }
//	type LineNo  struct{ domain.LongID }
type Identifier interface {
	comparable
	// IsZero reports whether the identifier is the zero (unassigned) value.
	IsZero() bool
	// String returns the canonical textual representation of the identifier.
	String() string
}

// UUIDBacked is implemented by identifiers whose storage representation is a UUID.
// Persistence adapters use it to convert typed identifiers to database values
// (equivalent to the C# ICommonBackedIdentifier.ToBaseType).
type UUIDBacked interface {
	BaseUUID() UUID
}

// LongBacked is implemented by identifiers whose storage representation is an int64
// (equivalent to the C# ICommonLongBackedIdentifier).
type LongBacked interface {
	BaseLong() int64
}

// UUID is an RFC 9562 universally unique identifier. It is comparable, so it can be used as a
// map key and compared with ==. The zero value is the nil UUID.
type UUID [16]byte

var (
	uuidMu  sync.Mutex
	uuidMS  uint64
	uuidSeq uint16
)

// NewUUID returns a new time-ordered (version 7) UUID. Version 7 keeps B-tree indexes compact
// on every supported database. UUIDs generated by one process are strictly increasing: within
// the same millisecond a 12-bit counter is used (RFC 9562, method 1), so ordering by id
// preserves creation order (e.g. outbox messages raised in the same millisecond).
func NewUUID() UUID {
	uuidMu.Lock()
	ms := uint64(time.Now().UnixMilli())
	if ms <= uuidMS {
		ms = uuidMS
		uuidSeq++
		if uuidSeq > 0x0fff {
			ms++
			uuidSeq = 0
		}
	} else {
		uuidSeq = 0
	}
	uuidMS = ms
	seq := uuidSeq
	uuidMu.Unlock()

	var u UUID
	binary.BigEndian.PutUint16(u[0:2], uint16(ms>>32))
	binary.BigEndian.PutUint32(u[2:6], uint32(ms))
	_, _ = rand.Read(u[8:])
	u[6] = 0x70 | byte(seq>>8)&0x0f // version 7 + counter high bits
	u[7] = byte(seq)
	u[8] = (u[8] & 0x3f) | 0x80 // RFC 9562 variant
	return u
}

// ParseUUID parses the canonical 36-character form, the 32-character hex form, or the braced form.
func ParseUUID(s string) (UUID, error) {
	var u UUID
	s = strings.TrimSuffix(strings.TrimPrefix(s, "{"), "}")
	switch len(s) {
	case 36:
		if s[8] != '-' || s[13] != '-' || s[18] != '-' || s[23] != '-' {
			return u, fmt.Errorf("%w: malformed uuid %q", ErrInvalidIdentity, s)
		}
		s = s[0:8] + s[9:13] + s[14:18] + s[19:23] + s[24:]
	case 32:
	default:
		return u, fmt.Errorf("%w: malformed uuid %q", ErrInvalidIdentity, s)
	}
	if _, err := hex.Decode(u[:], []byte(s)); err != nil {
		return UUID{}, fmt.Errorf("%w: malformed uuid %q", ErrInvalidIdentity, s)
	}
	return u, nil
}

// MustParseUUID is like ParseUUID but panics on error. Intended for constants and tests.
func MustParseUUID(s string) UUID {
	u, err := ParseUUID(s)
	if err != nil {
		panic(err)
	}
	return u
}

// UUIDFromBytes builds a UUID from its 16-byte big-endian (RFC) representation.
func UUIDFromBytes(b []byte) (UUID, error) {
	var u UUID
	if len(b) != len(u) {
		return u, fmt.Errorf("%w: uuid requires 16 bytes, got %d", ErrInvalidIdentity, len(b))
	}
	copy(u[:], b)
	return u, nil
}

// IsZero reports whether u is the nil UUID.
func (u UUID) IsZero() bool { return u == UUID{} }

// BaseUUID returns u itself. It lets typed identifiers that embed UUID satisfy UUIDBacked.
func (u UUID) BaseUUID() UUID { return u }

// Bytes returns the 16-byte big-endian representation.
func (u UUID) Bytes() []byte { return append([]byte(nil), u[:]...) }

// String returns the canonical lowercase 8-4-4-4-12 representation.
func (u UUID) String() string {
	var buf [36]byte
	hex.Encode(buf[0:8], u[0:4])
	buf[8] = '-'
	hex.Encode(buf[9:13], u[4:6])
	buf[13] = '-'
	hex.Encode(buf[14:18], u[6:8])
	buf[18] = '-'
	hex.Encode(buf[19:23], u[8:10])
	buf[23] = '-'
	hex.Encode(buf[24:], u[10:])
	return string(buf[:])
}

// MarshalText implements encoding.TextMarshaler so typed identifiers serialize as JSON strings.
func (u UUID) MarshalText() ([]byte, error) { return []byte(u.String()), nil }

// UnmarshalText implements encoding.TextUnmarshaler.
func (u *UUID) UnmarshalText(b []byte) error {
	parsed, err := ParseUUID(string(b))
	if err != nil {
		return err
	}
	*u = parsed
	return nil
}

// LongID is an int64-backed identifier for sequence or natural numeric keys.
// Embed it to declare typed numeric identifiers: type InvoiceNo struct{ domain.LongID }.
type LongID int64

// IsZero reports whether the identifier is unassigned (0).
func (l LongID) IsZero() bool { return l == 0 }

// BaseLong returns the underlying int64 so typed identifiers satisfy LongBacked.
func (l LongID) BaseLong() int64 { return int64(l) }

// String returns the decimal representation.
func (l LongID) String() string { return strconv.FormatInt(int64(l), 10) }
