// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/contact"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/party"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/predicate"
)

// ContactUpdate is the builder for updating Contact entities.
type ContactUpdate struct {
	config
	hooks    []Hook
	mutation *ContactMutation
}

// Where appends a list predicates to the ContactUpdate builder.
func (_u *ContactUpdate) Where(ps ...predicate.Contact) *ContactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *ContactUpdate) SetEmail(v string) *ContactUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ContactUpdate) SetNillableEmail(v *string) *ContactUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *ContactUpdate) SetPhone(v string) *ContactUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *ContactUpdate) SetNillablePhone(v *string) *ContactUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *ContactUpdate) ClearPhone() *ContactUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetCity sets the "city" field.
func (_u *ContactUpdate) SetCity(v string) *ContactUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *ContactUpdate) SetNillableCity(v *string) *ContactUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *ContactUpdate) ClearCity() *ContactUpdate {
	_u.mutation.ClearCity()
	return _u
}

// SetOwnerID sets the "owner" edge to the Party entity by ID.
func (_u *ContactUpdate) SetOwnerID(id int) *ContactUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the Party entity by ID if the given value is not nil.
func (_u *ContactUpdate) SetNillableOwnerID(id *int) *ContactUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the Party entity.
func (_u *ContactUpdate) SetOwner(v *Party) *ContactUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ContactMutation object of the builder.
func (_u *ContactUpdate) Mutation() *ContactMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Party entity.
func (_u *ContactUpdate) ClearOwner() *ContactUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContactUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContactUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := contact.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Contact.email": %w`, err)}
		}
	}
	return nil
}

func (_u *ContactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contact.Table, contact.Columns, sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(contact.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(contact.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(contact.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(contact.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(contact.FieldCity, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contact.OwnerTable,
			Columns: []string{contact.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(party.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contact.OwnerTable,
			Columns: []string{contact.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(party.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContactUpdateOne is the builder for updating a single Contact entity.
type ContactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContactMutation
}

// SetEmail sets the "email" field.
func (_u *ContactUpdateOne) SetEmail(v string) *ContactUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ContactUpdateOne) SetNillableEmail(v *string) *ContactUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *ContactUpdateOne) SetPhone(v string) *ContactUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *ContactUpdateOne) SetNillablePhone(v *string) *ContactUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *ContactUpdateOne) ClearPhone() *ContactUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetCity sets the "city" field.
func (_u *ContactUpdateOne) SetCity(v string) *ContactUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *ContactUpdateOne) SetNillableCity(v *string) *ContactUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *ContactUpdateOne) ClearCity() *ContactUpdateOne {
	_u.mutation.ClearCity()
	return _u
}

// SetOwnerID sets the "owner" edge to the Party entity by ID.
func (_u *ContactUpdateOne) SetOwnerID(id int) *ContactUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the Party entity by ID if the given value is not nil.
func (_u *ContactUpdateOne) SetNillableOwnerID(id *int) *ContactUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the Party entity.
func (_u *ContactUpdateOne) SetOwner(v *Party) *ContactUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ContactMutation object of the builder.
func (_u *ContactUpdateOne) Mutation() *ContactMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Party entity.
func (_u *ContactUpdateOne) ClearOwner() *ContactUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the ContactUpdate builder.
func (_u *ContactUpdateOne) Where(ps ...predicate.Contact) *ContactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContactUpdateOne) Select(field string, fields ...string) *ContactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Contact entity.
func (_u *ContactUpdateOne) Save(ctx context.Context) (*Contact, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContactUpdateOne) SaveX(ctx context.Context) *Contact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContactUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := contact.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Contact.email": %w`, err)}
		}
	}
	return nil
}

func (_u *ContactUpdateOne) sqlSave(ctx context.Context) (_node *Contact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contact.Table, contact.Columns, sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Contact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contact.FieldID)
		for _, f := range fields {
			if !contact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(contact.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(contact.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(contact.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(contact.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(contact.FieldCity, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contact.OwnerTable,
			Columns: []string{contact.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(party.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contact.OwnerTable,
			Columns: []string{contact.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(party.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Contact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
