// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/party"
)

// Party is the model entity for the Party schema.
type Party struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TaxID holds the value of the "tax_id" field.
	TaxID string `json:"tax_id,omitempty"`
	// LegalName holds the value of the "legal_name" field.
	LegalName string `json:"legal_name,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PartyQuery when eager-loading is set.
	Edges        PartyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PartyEdges holds the relations/edges for other nodes in the graph.
type PartyEdges struct {
	// Contacts holds the value of the contacts edge.
	Contacts []*Contact `json:"contacts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ContactsOrErr returns the Contacts value or an error if the edge
// was not loaded in eager-loading.
func (e PartyEdges) ContactsOrErr() ([]*Contact, error) {
	if e.loadedTypes[0] {
		return e.Contacts, nil
	}
	return nil, &NotLoadedError{edge: "contacts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Party) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case party.FieldIsActive:
			values[i] = new(sql.NullBool)
		case party.FieldID:
			values[i] = new(sql.NullInt64)
		case party.FieldTaxID, party.FieldLegalName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Party fields.
func (_m *Party) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case party.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case party.FieldTaxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_id", values[i])
			} else if value.Valid {
				_m.TaxID = value.String
			}
		case party.FieldLegalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field legal_name", values[i])
			} else if value.Valid {
				_m.LegalName = value.String
			}
		case party.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Party.
// This includes values selected through modifiers, order, etc.
func (_m *Party) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryContacts queries the "contacts" edge of the Party entity.
func (_m *Party) QueryContacts() *ContactQuery {
	return NewPartyClient(_m.config).QueryContacts(_m)
}

// Update returns a builder for updating this Party.
// Note that you need to call Party.Unwrap() before calling this method if this Party
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Party) Update() *PartyUpdateOne {
	return NewPartyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Party entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Party) Unwrap() *Party {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Party is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Party) String() string {
	var builder strings.Builder
	builder.WriteString("Party(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tax_id=")
	builder.WriteString(_m.TaxID)
	builder.WriteString(", ")
	builder.WriteString("legal_name=")
	builder.WriteString(_m.LegalName)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// Parties is a parsable slice of Party.
type Parties []*Party
