// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/contact"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/party"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/predicate"
)

// PartyUpdate is the builder for updating Party entities.
type PartyUpdate struct {
	config
	hooks    []Hook
	mutation *PartyMutation
}

// Where appends a list predicates to the PartyUpdate builder.
func (_u *PartyUpdate) Where(ps ...predicate.Party) *PartyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *PartyUpdate) SetTaxID(v string) *PartyUpdate {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *PartyUpdate) SetNillableTaxID(v *string) *PartyUpdate {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// SetLegalName sets the "legal_name" field.
func (_u *PartyUpdate) SetLegalName(v string) *PartyUpdate {
	_u.mutation.SetLegalName(v)
	return _u
}

// SetNillableLegalName sets the "legal_name" field if the given value is not nil.
func (_u *PartyUpdate) SetNillableLegalName(v *string) *PartyUpdate {
	if v != nil {
		_u.SetLegalName(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PartyUpdate) SetIsActive(v bool) *PartyUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PartyUpdate) SetNillableIsActive(v *bool) *PartyUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddContactIDs adds the "contacts" edge to the Contact entity by IDs.
func (_u *PartyUpdate) AddContactIDs(ids ...int) *PartyUpdate {
	_u.mutation.AddContactIDs(ids...)
	return _u
}

// AddContacts adds the "contacts" edges to the Contact entity.
func (_u *PartyUpdate) AddContacts(v ...*Contact) *PartyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContactIDs(ids...)
}

// Mutation returns the PartyMutation object of the builder.
func (_u *PartyUpdate) Mutation() *PartyMutation {
	return _u.mutation
}

// ClearContacts clears all "contacts" edges to the Contact entity.
func (_u *PartyUpdate) ClearContacts() *PartyUpdate {
	_u.mutation.ClearContacts()
	return _u
}

// RemoveContactIDs removes the "contacts" edge to Contact entities by IDs.
func (_u *PartyUpdate) RemoveContactIDs(ids ...int) *PartyUpdate {
	_u.mutation.RemoveContactIDs(ids...)
	return _u
}

// RemoveContacts removes "contacts" edges to Contact entities.
func (_u *PartyUpdate) RemoveContacts(v ...*Contact) *PartyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContactIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PartyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PartyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PartyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PartyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PartyUpdate) check() error {
	if v, ok := _u.mutation.TaxID(); ok {
		if err := party.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "Party.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LegalName(); ok {
		if err := party.LegalNameValidator(v); err != nil {
			return &ValidationError{Name: "legal_name", err: fmt.Errorf(`ent: validator failed for field "Party.legal_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PartyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(party.Table, party.Columns, sqlgraph.NewFieldSpec(party.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(party.FieldTaxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LegalName(); ok {
		_spec.SetField(party.FieldLegalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(party.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   party.ContactsTable,
			Columns: []string{party.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContactsIDs(); len(nodes) > 0 && !_u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   party.ContactsTable,
			Columns: []string{party.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   party.ContactsTable,
			Columns: []string{party.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{party.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PartyUpdateOne is the builder for updating a single Party entity.
type PartyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PartyMutation
}

// SetTaxID sets the "tax_id" field.
func (_u *PartyUpdateOne) SetTaxID(v string) *PartyUpdateOne {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *PartyUpdateOne) SetNillableTaxID(v *string) *PartyUpdateOne {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// SetLegalName sets the "legal_name" field.
func (_u *PartyUpdateOne) SetLegalName(v string) *PartyUpdateOne {
	_u.mutation.SetLegalName(v)
	return _u
}

// SetNillableLegalName sets the "legal_name" field if the given value is not nil.
func (_u *PartyUpdateOne) SetNillableLegalName(v *string) *PartyUpdateOne {
	if v != nil {
		_u.SetLegalName(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PartyUpdateOne) SetIsActive(v bool) *PartyUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PartyUpdateOne) SetNillableIsActive(v *bool) *PartyUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddContactIDs adds the "contacts" edge to the Contact entity by IDs.
func (_u *PartyUpdateOne) AddContactIDs(ids ...int) *PartyUpdateOne {
	_u.mutation.AddContactIDs(ids...)
	return _u
}

// AddContacts adds the "contacts" edges to the Contact entity.
func (_u *PartyUpdateOne) AddContacts(v ...*Contact) *PartyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContactIDs(ids...)
}

// Mutation returns the PartyMutation object of the builder.
func (_u *PartyUpdateOne) Mutation() *PartyMutation {
	return _u.mutation
}

// ClearContacts clears all "contacts" edges to the Contact entity.
func (_u *PartyUpdateOne) ClearContacts() *PartyUpdateOne {
	_u.mutation.ClearContacts()
	return _u
}

// RemoveContactIDs removes the "contacts" edge to Contact entities by IDs.
func (_u *PartyUpdateOne) RemoveContactIDs(ids ...int) *PartyUpdateOne {
	_u.mutation.RemoveContactIDs(ids...)
	return _u
}

// RemoveContacts removes "contacts" edges to Contact entities.
func (_u *PartyUpdateOne) RemoveContacts(v ...*Contact) *PartyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContactIDs(ids...)
}

// Where appends a list predicates to the PartyUpdate builder.
func (_u *PartyUpdateOne) Where(ps ...predicate.Party) *PartyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PartyUpdateOne) Select(field string, fields ...string) *PartyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Party entity.
func (_u *PartyUpdateOne) Save(ctx context.Context) (*Party, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PartyUpdateOne) SaveX(ctx context.Context) *Party {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PartyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PartyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PartyUpdateOne) check() error {
	if v, ok := _u.mutation.TaxID(); ok {
		if err := party.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "Party.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LegalName(); ok {
		if err := party.LegalNameValidator(v); err != nil {
			return &ValidationError{Name: "legal_name", err: fmt.Errorf(`ent: validator failed for field "Party.legal_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PartyUpdateOne) sqlSave(ctx context.Context) (_node *Party, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(party.Table, party.Columns, sqlgraph.NewFieldSpec(party.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Party.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, party.FieldID)
		for _, f := range fields {
			if !party.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != party.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(party.FieldTaxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LegalName(); ok {
		_spec.SetField(party.FieldLegalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(party.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   party.ContactsTable,
			Columns: []string{party.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContactsIDs(); len(nodes) > 0 && !_u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   party.ContactsTable,
			Columns: []string{party.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   party.ContactsTable,
			Columns: []string{party.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Party{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{party.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
