// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/contact"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/party"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescEmail is the schema descriptor for email field.
	contactDescEmail := contactFields[0].Descriptor()
	// contact.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	contact.EmailValidator = contactDescEmail.Validators[0].(func(string) error)
	partyFields := schema.Party{}.Fields()
	_ = partyFields
	// partyDescTaxID is the schema descriptor for tax_id field.
	partyDescTaxID := partyFields[0].Descriptor()
	// party.TaxIDValidator is a validator for the "tax_id" field. It is called by the builders before save.
	party.TaxIDValidator = partyDescTaxID.Validators[0].(func(string) error)
	// partyDescLegalName is the schema descriptor for legal_name field.
	partyDescLegalName := partyFields[1].Descriptor()
	// party.LegalNameValidator is a validator for the "legal_name" field. It is called by the builders before save.
	party.LegalNameValidator = partyDescLegalName.Validators[0].(func(string) error)
	// partyDescIsActive is the schema descriptor for is_active field.
	partyDescIsActive := partyFields[2].Descriptor()
	// party.DefaultIsActive holds the default value on creation for the is_active field.
	party.DefaultIsActive = partyDescIsActive.Default.(bool)
}
