// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// Party is the predicate function for party builders.
type Party func(*sql.Selector)
