// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContactsColumns holds the columns for the "contacts" table.
	ContactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "city", Type: field.TypeString, Nullable: true},
		{Name: "party_contacts", Type: field.TypeInt, Nullable: true},
	}
	// ContactsTable holds the schema information for the "contacts" table.
	ContactsTable = &schema.Table{
		Name:       "contacts",
		Columns:    ContactsColumns,
		PrimaryKey: []*schema.Column{ContactsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "contacts_parties_contacts",
				Columns:    []*schema.Column{ContactsColumns[4]},
				RefColumns: []*schema.Column{PartiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PartiesColumns holds the columns for the "parties" table.
	PartiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tax_id", Type: field.TypeString, Unique: true},
		{Name: "legal_name", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// PartiesTable holds the schema information for the "parties" table.
	PartiesTable = &schema.Table{
		Name:       "parties",
		Columns:    PartiesColumns,
		PrimaryKey: []*schema.Column{PartiesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContactsTable,
		PartiesTable,
	}
)

func init() {
	ContactsTable.ForeignKeys[0].RefTable = PartiesTable
}
