// Code generated by ent, DO NOT EDIT.

package party

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Party {
	return predicate.Party(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Party {
	return predicate.Party(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Party {
	return predicate.Party(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Party {
	return predicate.Party(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Party {
	return predicate.Party(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Party {
	return predicate.Party(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Party {
	return predicate.Party(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Party {
	return predicate.Party(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Party {
	return predicate.Party(sql.FieldLTE(FieldID, id))
}

// TaxID applies equality check predicate on the "tax_id" field. It's identical to TaxIDEQ.
func TaxID(v string) predicate.Party {
	return predicate.Party(sql.FieldEQ(FieldTaxID, v))
}

// LegalName applies equality check predicate on the "legal_name" field. It's identical to LegalNameEQ.
func LegalName(v string) predicate.Party {
	return predicate.Party(sql.FieldEQ(FieldLegalName, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Party {
	return predicate.Party(sql.FieldEQ(FieldIsActive, v))
}

// TaxIDEQ applies the EQ predicate on the "tax_id" field.
func TaxIDEQ(v string) predicate.Party {
	return predicate.Party(sql.FieldEQ(FieldTaxID, v))
}

// TaxIDNEQ applies the NEQ predicate on the "tax_id" field.
func TaxIDNEQ(v string) predicate.Party {
	return predicate.Party(sql.FieldNEQ(FieldTaxID, v))
}

// TaxIDIn applies the In predicate on the "tax_id" field.
func TaxIDIn(vs ...string) predicate.Party {
	return predicate.Party(sql.FieldIn(FieldTaxID, vs...))
}

// TaxIDNotIn applies the NotIn predicate on the "tax_id" field.
func TaxIDNotIn(vs ...string) predicate.Party {
	return predicate.Party(sql.FieldNotIn(FieldTaxID, vs...))
}

// TaxIDGT applies the GT predicate on the "tax_id" field.
func TaxIDGT(v string) predicate.Party {
	return predicate.Party(sql.FieldGT(FieldTaxID, v))
}

// TaxIDGTE applies the GTE predicate on the "tax_id" field.
func TaxIDGTE(v string) predicate.Party {
	return predicate.Party(sql.FieldGTE(FieldTaxID, v))
}

// TaxIDLT applies the LT predicate on the "tax_id" field.
func TaxIDLT(v string) predicate.Party {
	return predicate.Party(sql.FieldLT(FieldTaxID, v))
}

// TaxIDLTE applies the LTE predicate on the "tax_id" field.
func TaxIDLTE(v string) predicate.Party {
	return predicate.Party(sql.FieldLTE(FieldTaxID, v))
}

// TaxIDContains applies the Contains predicate on the "tax_id" field.
func TaxIDContains(v string) predicate.Party {
	return predicate.Party(sql.FieldContains(FieldTaxID, v))
}

// TaxIDHasPrefix applies the HasPrefix predicate on the "tax_id" field.
func TaxIDHasPrefix(v string) predicate.Party {
	return predicate.Party(sql.FieldHasPrefix(FieldTaxID, v))
}

// TaxIDHasSuffix applies the HasSuffix predicate on the "tax_id" field.
func TaxIDHasSuffix(v string) predicate.Party {
	return predicate.Party(sql.FieldHasSuffix(FieldTaxID, v))
}

// TaxIDEqualFold applies the EqualFold predicate on the "tax_id" field.
func TaxIDEqualFold(v string) predicate.Party {
	return predicate.Party(sql.FieldEqualFold(FieldTaxID, v))
}

// TaxIDContainsFold applies the ContainsFold predicate on the "tax_id" field.
func TaxIDContainsFold(v string) predicate.Party {
	return predicate.Party(sql.FieldContainsFold(FieldTaxID, v))
}

// LegalNameEQ applies the EQ predicate on the "legal_name" field.
func LegalNameEQ(v string) predicate.Party {
	return predicate.Party(sql.FieldEQ(FieldLegalName, v))
}

// LegalNameNEQ applies the NEQ predicate on the "legal_name" field.
func LegalNameNEQ(v string) predicate.Party {
	return predicate.Party(sql.FieldNEQ(FieldLegalName, v))
}

// LegalNameIn applies the In predicate on the "legal_name" field.
func LegalNameIn(vs ...string) predicate.Party {
	return predicate.Party(sql.FieldIn(FieldLegalName, vs...))
}

// LegalNameNotIn applies the NotIn predicate on the "legal_name" field.
func LegalNameNotIn(vs ...string) predicate.Party {
	return predicate.Party(sql.FieldNotIn(FieldLegalName, vs...))
}

// LegalNameGT applies the GT predicate on the "legal_name" field.
func LegalNameGT(v string) predicate.Party {
	return predicate.Party(sql.FieldGT(FieldLegalName, v))
}

// LegalNameGTE applies the GTE predicate on the "legal_name" field.
func LegalNameGTE(v string) predicate.Party {
	return predicate.Party(sql.FieldGTE(FieldLegalName, v))
}

// LegalNameLT applies the LT predicate on the "legal_name" field.
func LegalNameLT(v string) predicate.Party {
	return predicate.Party(sql.FieldLT(FieldLegalName, v))
}

// LegalNameLTE applies the LTE predicate on the "legal_name" field.
func LegalNameLTE(v string) predicate.Party {
	return predicate.Party(sql.FieldLTE(FieldLegalName, v))
}

// LegalNameContains applies the Contains predicate on the "legal_name" field.
func LegalNameContains(v string) predicate.Party {
	return predicate.Party(sql.FieldContains(FieldLegalName, v))
}

// LegalNameHasPrefix applies the HasPrefix predicate on the "legal_name" field.
func LegalNameHasPrefix(v string) predicate.Party {
	return predicate.Party(sql.FieldHasPrefix(FieldLegalName, v))
}

// LegalNameHasSuffix applies the HasSuffix predicate on the "legal_name" field.
func LegalNameHasSuffix(v string) predicate.Party {
	return predicate.Party(sql.FieldHasSuffix(FieldLegalName, v))
}

// LegalNameEqualFold applies the EqualFold predicate on the "legal_name" field.
func LegalNameEqualFold(v string) predicate.Party {
	return predicate.Party(sql.FieldEqualFold(FieldLegalName, v))
}

// LegalNameContainsFold applies the ContainsFold predicate on the "legal_name" field.
func LegalNameContainsFold(v string) predicate.Party {
	return predicate.Party(sql.FieldContainsFold(FieldLegalName, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Party {
	return predicate.Party(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Party {
	return predicate.Party(sql.FieldNEQ(FieldIsActive, v))
}

// HasContacts applies the HasEdge predicate on the "contacts" edge.
func HasContacts() predicate.Party {
	return predicate.Party(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ContactsTable, ContactsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContactsWith applies the HasEdge predicate on the "contacts" edge with a given conditions (other predicates).
func HasContactsWith(preds ...predicate.Contact) predicate.Party {
	return predicate.Party(func(s *sql.Selector) {
		step := newContactsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Party) predicate.Party {
	return predicate.Party(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Party) predicate.Party {
	return predicate.Party(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Party) predicate.Party {
	return predicate.Party(sql.NotPredicates(p))
}
