package integration

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"testing"
	"time"

	binfra "github.com/jhermoso/karpo-fw-go/contexts/billing/infrastructure"
	yinfra "github.com/jhermoso/karpo-fw-go/contexts/payments/infrastructure"
	rinfra "github.com/jhermoso/karpo-fw-go/contexts/receivables/infrastructure"
	"github.com/jhermoso/karpo-fw-go/contexts/treasury"
	tapp "github.com/jhermoso/karpo-fw-go/contexts/treasury/application"
	tdomain "github.com/jhermoso/karpo-fw-go/contexts/treasury/domain"
	tinfra "github.com/jhermoso/karpo-fw-go/contexts/treasury/infrastructure"
	"github.com/jhermoso/karpo-fw-go/pkg/application/authz"
	fw "github.com/jhermoso/karpo-fw-go/pkg/domain"
	"github.com/jhermoso/karpo-fw-go/pkg/domain/vocab"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/hotswap"
	"github.com/jhermoso/karpo-fw-go/pkg/persistence/sqlrepo"
	"github.com/jhermoso/karpo-fw-go/pkg/time/fake"
)

// bankWorld plays the contexts Treasury asks.
type bankWorld struct {
	due []tdomain.DueItem
	pay []tdomain.PayableDue
}

func (o *bankWorld) DueItems(context.Context, tdomain.OrganizationID, vocab.Date) ([]tdomain.DueItem, error) {
	return o.due, nil
}

func (o *bankWorld) DueForTransfer(context.Context, tdomain.OrganizationID, vocab.Date) ([]tdomain.PayableDue, int, error) {
	return o.pay, 0, nil
}

func (o *bankWorld) Identities(_ context.Context, parties []tdomain.PartyID) (map[tdomain.PartyID]tdomain.Identity, error) {
	out := map[tdomain.PartyID]tdomain.Identity{}
	for _, p := range parties {
		out[p] = tdomain.Identity{Name: "Acme, S.A.", NIF: "A58818501"}
	}
	return out, nil
}

// norma43May builds the Cuaderno 43 file of account 2100 0813 0123456789 for May 2026: opening
// balance of 10,000.00, a remittance credited, an order of transfers charged and a fee.
func norma43May() string {
	amount := func(c int64) string {
		key := "2"
		if c < 0 {
			key, c = "1", -c
		}
		return key + fmt.Sprintf("%014d", c)
	}
	pad := func(s string, n int) string { return s + strings.Repeat(" ", n-len([]rune(s))) }
	var b strings.Builder
	b.WriteString("11" + "2100" + "0813" + "0123456789" + "260501" + "260531" + amount(1000000) + "978" + "3" + pad("ACME SA", 26) + "   \r\n")
	for _, m := range []struct {
		day     int
		cents   int64
		concept string
	}{{5, 36300, "ADEUDOS SEPA REMESA"}, {12, -106000, "ORDEN DE TRANSFERENCIAS"}, {29, -250, "COMISIÓN DE MANTENIMIENTO"}} {
		day := fmt.Sprintf("2605%02d", m.day)
		b.WriteString("22" + "    " + "0813" + day + day + "02" + "011" + amount(m.cents) + "0000000000" + pad("REF", 12) + pad("", 16) + "\r\n")
		b.WriteString("23" + "01" + pad(m.concept, 38) + pad("", 38) + "\r\n")
	}
	b.WriteString("33" + "2100" + "0813" + "0123456789" + fmt.Sprintf("%05d%014d%05d%014d", 2, 106250, 1, 36300) + amount(930050) + "978" + "    \r\n")
	b.WriteString("88" + strings.Repeat("9", 18) + "000008\r\n")
	return b.String()
}

// TestStatementsContext runs the bank statements of Treasury on every engine: a Cuaderno 43 file
// recorded whole, the continuity between statements, the round trip of the movements in order,
// the automatic reconciliation against a remittance and a transfer order generated by the use
// cases, the reconciliation by hand (and that nothing is reconciled twice, searched through the
// child rows), the release, and the search of statements with movements pending.
func TestStatementsContext(t *testing.T) {
	for _, e := range engines {
		if e.name == "oracle-dotnet-guids" {
			continue
		}
		t.Run(e.name, func(t *testing.T) {
			db := open(t, e)
			ctx := context.Background()
			yinfra.DropAll(ctx, db)
			tinfra.DropAll(ctx, db)
			rinfra.DropAll(ctx, db)
			binfra.DropAll(ctx, db)
			m, err := sqlrepo.NewMigrator(db, []sqlrepo.MigrationSet{tinfra.Migrations()})
			if err != nil {
				t.Fatal(err)
			}
			if _, err := m.Migrate(ctx); err != nil {
				t.Fatal(err)
			}
			sw := hotswap.New(db)
			world := &bankWorld{}
			tm := treasury.Compose(sw, world, world, world)
			must := func(err error) {
				t.Helper()
				if err != nil {
					t.Fatal(err)
				}
			}
			violates := func(err error, code string) {
				t.Helper()
				var rv *fw.RuleViolationError
				if !errors.As(err, &rv) || rv.Code != code {
					t.Fatalf("want %s: %v", code, err)
				}
			}
			admin, _ := authz.NewContext(authz.Context{Subject: fw.NewUUID(), SubjectName: "admin", Kind: authz.Service, Permissions: []authz.Permission{authz.Wildcard}})
			admin.GlobalAdmin = true
			actx := authz.WithContext(ctx, admin)
			svc := tm.Service
			acme, debtor := fw.NewUUID().String(), fw.NewUUID()
			day := func(m time.Month, d int) vocab.Date { return vocab.MustDate(2026, m, d) }

			main, err := svc.OpenAccount.Handle(actx, tapp.OpenAccount{Owner: acme, IBAN: "ES7921000813610123456789", Alias: "Principal", Collections: true,
				Payments: true, Opened: vocab.MustDate(2020, 1, 1)})
			must(err)
			_, err = svc.RegisterMandate.Handle(actx, tapp.RegisterMandate{Creditor: acme, Debtor: debtor.String(), IBAN: "ES6621000418401234567891",
				Reference: "M-1", Scheme: "CORE", Signed: day(1, 1)})
			must(err)
			iban, _ := vocab.NewIBAN("ES6621000418401234567891")
			restore := fw.SetClock(fake.New(time.Date(2026, 5, 1, 9, 0, 0, 0, time.UTC)))
			world.due = []tdomain.DueItem{{Invoice: tdomain.InvoiceID{UUID: fw.NewUUID()}, Number: "A-2026-000001", Customer: tdomain.PartyID{UUID: debtor},
				Installment: 1, Due: day(5, 5), Open: vocab.MustDecimal("363.00")}}
			rem, err := svc.Propose.Handle(actx, tapp.ProposeRemittance{Creditor: acme, Account: main.ID, Scheme: "CORE", CollectionDate: day(5, 5), DueTo: day(5, 5)})
			must(err)
			rid, _ := tdomain.ParseRemittanceID(rem.ID)
			_, err = svc.Generate.Handle(actx, tapp.GenerateRemittance{ID: rid})
			must(err)
			world.pay = []tdomain.PayableDue{{Payable: tdomain.PayableID{UUID: fw.NewUUID()}, Kind: "supplier-invoice", Document: "FR-2026-000001",
				Payee: fw.NewUUID().String(), Due: day(5, 12), PayTo: []tdomain.PayableAccount{{IBAN: iban, Amount: vocab.MustDecimal("1060.00")}}}}
			order, err := svc.ProposeTransfers.Handle(actx, tapp.ProposeTransfers{Debtor: acme, Account: main.ID, ExecutionDate: day(5, 12), DueTo: day(5, 12)})
			must(err)
			oid, _ := tdomain.ParseTransferOrderID(order.ID)
			_, err = svc.GenerateTransfers.Handle(actx, tapp.GenerateTransfers{ID: oid})
			must(err)
			restore()

			_, err = svc.ImportNorma43.Handle(actx, tapp.ImportNorma43{Owner: acme, Content: strings.Replace(norma43May(), "0123456789", "9999999999", 2)})
			violates(err, "treasury.unknown_account")
			files, err := svc.ImportNorma43.Handle(actx, tapp.ImportNorma43{Owner: acme, Content: norma43May()})
			if err != nil || len(files) != 1 || files[0].Movements != 3 || files[0].Pending != 3 || files[0].Closing != "9300.50" {
				t.Fatalf("May: %+v %v", files, err)
			}
			_, err = svc.ImportNorma43.Handle(actx, tapp.ImportNorma43{Owner: acme, Content: norma43May()})
			violates(err, "treasury.statement_overlap")
			june := tapp.ImportStatement{Account: main.ID, From: day(6, 1), To: day(6, 30), Opening: "9000.00", Closing: "9363.00",
				Lines: []tapp.MovementInput{{Date: day(6, 2), Amount: "363.00", Concept: "Adeudos SEPA", Reference: "R-2"}}}
			_, err = svc.ImportStatement.Handle(actx, june)
			violates(err, "treasury.statement_gap")
			june.Opening, june.Closing = "9300.50", "9663.50"
			jun, err := svc.ImportStatement.Handle(actx, june)
			must(err)

			mid, _ := tdomain.ParseStatementID(files[0].ID)
			jid, _ := tdomain.ParseStatementID(jun.ID)
			auto, err := svc.AutoReconcile.Handle(actx, tapp.AutoReconcile{ID: mid})
			if err != nil || auto.Matched != 2 || auto.Pending != 1 || auto.Lines[0].MatchRef != rem.ID || auto.Lines[1].MatchKind != "transfer-order" ||
				auto.Lines[1].MatchRef != order.ID {
				t.Fatalf("automatic: %+v %v", auto, err)
			}
			// The remittance already explains a movement of May: found through the child rows.
			_, err = svc.Reconcile.Handle(actx, tapp.ReconcileLine{ID: jid, Line: 1, Kind: "remittance", Ref: rem.ID})
			violates(err, "treasury.match_taken")
			if a, err := svc.AutoReconcile.Handle(actx, tapp.AutoReconcile{ID: jid}); err != nil || a.Matched != 0 {
				t.Fatalf("June automatic: %+v %v", a, err)
			}
			_, err = svc.Reconcile.Handle(actx, tapp.ReconcileLine{ID: mid, Line: 3, Kind: "remittance", Ref: rem.ID})
			violates(err, "treasury.match_amount")
			done, err := svc.Reconcile.Handle(actx, tapp.ReconcileLine{ID: mid, Line: 3, Kind: "other", Note: "Comisión de mantenimiento"})
			if err != nil || done.Pending != 0 {
				t.Fatalf("the fee: %+v %v", done, err)
			}

			got, err := svc.GetStatement.Handle(actx, tapp.GetStatement{ID: mid})
			if err != nil || got.Account != main.ID || got.Owner != acme || got.From != "2026-05-01" || got.To != "2026-05-31" || got.Opening != "10000.00" ||
				len(got.Lines) != 3 || got.Lines[0].Line != 1 || got.Lines[0].Date != "2026-05-05" || got.Lines[0].Amount != "363.00" ||
				got.Lines[0].Concept != "ADEUDOS SEPA REMESA" || got.Lines[0].Reference != "REF" || got.Lines[0].MatchKind != "remittance" ||
				got.Lines[1].Amount != "-1060.00" || got.Lines[2].Concept != "COMISIÓN DE MANTENIMIENTO" || got.Lines[2].MatchKind != "other" ||
				got.Lines[2].MatchRef != "" || got.Lines[2].MatchNote != "Comisión de mantenimiento" {
				t.Fatalf("May round trip: %+v %v", got, err)
			}
			// Released, the remittance may explain the movement of June.
			_, err = svc.Release.Handle(actx, tapp.ReleaseLine{ID: mid, Line: 1})
			must(err)
			j, err := svc.Reconcile.Handle(actx, tapp.ReconcileLine{ID: jid, Line: 1, Kind: "remittance", Ref: rem.ID})
			if err != nil || j.Pending != 0 || j.Lines[0].Reference != "R-2" {
				t.Fatalf("June by hand: %+v %v", j, err)
			}
			pending, err := svc.SearchStatements.Handle(actx, tapp.SearchStatements{Owner: acme, Pending: true})
			if err != nil || len(pending.Items) != 1 || pending.Items[0].ID != files[0].ID || pending.Items[0].Pending != 1 {
				t.Fatalf("pending: %+v %v", pending.Items, err)
			}
			all, err := svc.SearchStatements.Handle(actx, tapp.SearchStatements{Account: main.ID})
			if err != nil || len(all.Items) != 2 || all.Items[1].ID != jun.ID {
				t.Fatalf("statements: %+v %v", all.Items, err)
			}
		})
	}
}
